//
//  Localized.swift
//  PrettyMessage
//
//  Created by Emil Shpeklord on 07.06.2020.
//  Copyright © 2020 Бизнес в стиле .RU. All rights reserved.
//

import Foundation

class Localize{
    let dict = [
        "pesdk_adjustments_accessibility_blacksIntensitySliderLabel": "Точки черного",
        "pesdk_adjustments_accessibility_brightnessIntensitySliderLabel": "Яркость",
        "pesdk_adjustments_accessibility_clarityIntensitySliderLabel": "Четкость",
        "pesdk_adjustments_accessibility_contrastIntensitySliderLabel": "Констраст",
        "pesdk_adjustments_accessibility_exposureIntensitySliderLabel": "Экспозиция",
        "pesdk_adjustments_accessibility_gammaIntensitySliderLabel": "Гамма",
        "pesdk_adjustments_accessibility_highlightsIntensitySliderLabel": "Блик",
        "pesdk_adjustments_accessibility_saturationIntensitySliderLabel": "Насыщенность",
        "pesdk_adjustments_accessibility_shadowsIntensitySliderLabel": "Тени",
        "pesdk_adjustments_accessibility_sharpnessIntensitySliderLabel": "Резкость",
        "pesdk_adjustments_accessibility_temperatureIntensitySliderLabel": "Температура",
        "pesdk_adjustments_accessibility_whitesIntensitySliderLabel": "Точки белого",
        "pesdk_adjustments_button_blacksTool": "Точки черного",
        "pesdk_adjustments_button_brightnessTool": "Яркость",
        "pesdk_adjustments_button_clarityTool": "Четкость",
        "pesdk_adjustments_button_contrastTool": "Контраст",
        "pesdk_adjustments_button_exposureTool": "Экспозиция",
        "pesdk_adjustments_button_gammaTool": "Гамма",
        "pesdk_adjustments_button_highlightsTool": "Блики",
        "pesdk_adjustments_button_reset": "Сброс",
        "pesdk_adjustments_button_saturationTool": "Насыщенность",
        "pesdk_adjustments_button_shadowsTool": "Тени",
        "pesdk_adjustments_button_sharpnessTool": "Резкость",
        "pesdk_adjustments_button_temperatureTool": "Температура",
        "pesdk_adjustments_button_whitesTool": "Точки белого",
        "pesdk_adjustments_title_name": "Параметры",
        "pesdk_autoEnhancement_title_name": "Magic",
        "pesdk_brush_accessibility_brushHardnessSliderLabel": "Жесткость кисти",
        "pesdk_brush_accessibility_brushSizeSliderLabel": "Размер кисти",
        "pesdk_brush_accessibility_canvasViewHint": "Дважды нажмите и удерживайте, чтобы рисовать",
        "pesdk_brush_accessibility_canvasViewLabel": "Холст",
        "pesdk_brush_accessibility_colorButtonLabel": "Цвет",
        "pesdk_brush_accessibility_hardnessButtonLabel": "Жесткость",
        "pesdk_brush_accessibility_sizeButtonLabel": "Размер",
        "pesdk_brush_button_color": "Цвет",
        "pesdk_brush_button_hardness": "Жесткость",
        "pesdk_brush_button_size": "Размер",
        "pesdk_brush_title_brushColor": "Цвет кисти",
        "pesdk_brush_title_name": "Кисть",
        "pesdk_camera_accessibility_cameraChooserButtonHint": "Переключение между передней и задней камерой",
        "pesdk_camera_accessibility_cameraChooserButtonLabel": "Выбор камеры",
        "pesdk_camera_accessibility_cameraRollButtonLabel": "Просмотр фотографий",
        "pesdk_camera_accessibility_cancelButtonLabel": "Отмена",
        "pesdk_camera_accessibility_filterButtonHint": "Показать или скрыть список фильтров",
        "pesdk_camera_accessibility_filterButtonLabel": "Фильтры",
        "pesdk_camera_accessibility_filterIntensitySliderLabel": "Интенсивность Фильтра",
        "pesdk_camera_accessibility_flashModeAutomaticButtonLabel": "Вспышка, авто",
        "pesdk_camera_accessibility_flashModeButtonHint": "Переключение между режимами вспышки",
        "pesdk_camera_accessibility_flashModeOffButtonLabel": "Вспышка, выкл",
        "pesdk_camera_accessibility_flashModeOnButtonLabel": "Вспышка, вкл",
        "pesdk_camera_accessibility_recordVideoButtonLabel": "Запись видео",
        "pesdk_camera_accessibility_recordVideoStopButtonLabel": "Остановить запись видео",
        "pesdk_camera_accessibility_takePictureButtonLabel": "Сфотографировать",
        "pesdk_camera_accessibility_viewfinderLabel": "Видеоискатель",
        "pesdk_camera_button_photoRecordingMode": "ФОТО",
        "pesdk_camera_button_settings": "Настройки",
        "pesdk_camera_button_videoRecordingMode": "Видео",
        "pesdk_camera_text_noPermissionsAlert": "Разрешение на использование камеры необходимо, пожалуйста, измените в настройках конфиденциальности.",
        "pesdk_camera_title_noPermissionsAlert": "Нет разрешения",
        "pesdk_common_accessibility_addButtonLabel": "Добавить",
        "pesdk_common_accessibility_alphaAndHuePickerHint": "Дважды нажмите и удерживайте для перемещения",
        "pesdk_common_accessibility_alphaPickerLabel": "Alpha Picker",
        "pesdk_common_accessibility_applyChangesButtonLabel": "Применить изменения",
        "pesdk_common_accessibility_bringToFrontButtonLabel": "На передний план",
        "pesdk_common_accessibility_deleteButtonLabel": "Удалить",
        "pesdk_common_accessibility_discardChangesButtonLabel": "Отменить изменения",
        "pesdk_common_accessibility_flipButtonLabel": "Повернуть",
        "pesdk_common_accessibility_huePickerLabel": "Подборщик Оттенков",
        "pesdk_common_accessibility_invertButtonLabel": "Инвертировать",
        "pesdk_common_accessibility_redoButtonLabel": "Повторить",
        "pesdk_common_accessibility_saturationBrightnessPickerHint": "Дважды нажмите и удерживайте для перемещения",
        "pesdk_common_accessibility_saturationBrightnessPickerLabel": "Насыщенность и Яркость",
        "pesdk_common_accessibility_undoButtonLabel": "Отмена",
        "pesdk_common_button_add": "Добавить",
        "pesdk_common_button_cancel": "Отмена",
        "pesdk_common_button_retry": "Повторить попытку",
        "pesdk_common_title_aquamarinColor": "Аквамарин",
        "pesdk_common_title_blackColor": "Черный",
        "pesdk_common_title_blueColor": "Синий",
        "pesdk_common_title_error": "Ошибка",
        "pesdk_common_title_goldColor": "Золотой",
        "pesdk_common_title_grayColor": "Серый",
        "pesdk_common_title_greenColor": "Зеленый",
        "pesdk_common_title_lightBlueColor": "Голубой",
        "pesdk_common_title_loadingSpinner": "Загрузка",
        "pesdk_common_title_oliveColor": "Оливковый",
        "pesdk_common_title_orangeColor": "Оранжевый",
        "pesdk_common_title_orchidColor": "Орхидеевый",
        "pesdk_common_title_pinkColor": "Розовый",
        "pesdk_common_title_pipettableColor": "Пипетка",
        "pesdk_common_title_purpleColor": "Фиолетовый",
        "pesdk_common_title_redColor": "Красный",
        "pesdk_common_title_transparentColor": "Прозрачный",
        "pesdk_common_title_whiteColor": "Белый",
        "pesdk_common_title_yellowColor": "Желтый",
        "pesdk_editor_accessibility_discardPhotoButtonLabel": "Сбросить фото",
        "pesdk_editor_accessibility_photoLabel": "Фото",
        "pesdk_editor_accessibility_savePhotoButtonLabel": "Сохранить Фото",
        "pesdk_editor_button_discardChanges": "Сбросить изменения",
        "pesdk_editor_text_discardChangesAlert": "Все изменения будут потеряны.",
        "pesdk_editor_title_discardChangesAlert": "Сбросить изменения?",
        "pesdk_editor_title_exportingVideoSpinner": "Экспортирую видео",
        "pesdk_editor_title_loadingAssetSpinner": "Загрузка",
        "pesdk_editor_title_loadingImageSpinner": "Загрузка изображения",
        "pesdk_editor_title_loadingVideoSpinner": "Загрузка видео",
        "pesdk_editor_title_name": "Редактор",
        "pesdk_editor_title_savingImageSpinner": "Сохранение изображения",
        "pesdk_filter_accessibility_filterIntensitySliderLabel": "Интенсивность фильтра",
        "pesdk_filter_asset_669": "Green Gap",
        "pesdk_filter_asset_70s": "Seventies",
        "pesdk_filter_asset_80s": "Low Fire",
        "pesdk_filter_asset_ad1920": "1920 A.D.",
        "pesdk_filter_asset_ancient": "Ancient",
        "pesdk_filter_asset_bBlue": "Joran",
        "pesdk_filter_asset_bleached": "Kalmen",
        "pesdk_filter_asset_blueShade": "Zephyr",
        "pesdk_filter_asset_blues": "Polaroid",
        "pesdk_filter_asset_breeze": "Levante",
        "pesdk_filter_asset_bw": "Greyed",
        "pesdk_filter_asset_bwFilterCategory": "B&W",
        "pesdk_filter_asset_candy": "Candy",
        "pesdk_filter_asset_carb": "High Carb",
        "pesdk_filter_asset_celsius": "Inferno",
        "pesdk_filter_asset_chest": "Chestnut",
        "pesdk_filter_asset_classic": "Classic",
        "pesdk_filter_asset_coldFilterCategory": "Cold",
        "pesdk_filter_asset_colorful": "Colorful",
        "pesdk_filter_asset_cool": "Snappy",
        "pesdk_filter_asset_creamy": "Creamy",
        "pesdk_filter_asset_duotoneBreezy": "Breezy",
        "pesdk_filter_asset_duotoneClash": "Clash",
        "pesdk_filter_asset_duotoneDeepBlue": "Deep Blue",
        "pesdk_filter_asset_duotoneDesert": "Desert",
        "pesdk_filter_asset_duotoneFilterCategory": "Duotone",
        "pesdk_filter_asset_duotoneFrog": "Frog",
        "pesdk_filter_asset_duotonePeach": "Peach",
        "pesdk_filter_asset_duotonePlum": "Plum",
        "pesdk_filter_asset_duotoneSunset": "Sunset",
        "pesdk_filter_asset_dynamic": "Pebble",
        "pesdk_filter_asset_elder": "Colla",
        "pesdk_filter_asset_evening": "Sunrise",
        "pesdk_filter_asset_fall": "Moss",
        "pesdk_filter_asset_fixie": "Fixie",
        "pesdk_filter_asset_food": "Food",
        "pesdk_filter_asset_fridge": "Fridge",
        "pesdk_filter_asset_front": "Sunny 70s",
        "pesdk_filter_asset_glam": "Glam",
        "pesdk_filter_asset_goblin": "Gobblin",
        "pesdk_filter_asset_hicon": "Hicon",
        "pesdk_filter_asset_k1": "K1",
        "pesdk_filter_asset_k2": "Flat Black",
        "pesdk_filter_asset_k6": "K6",
        "pesdk_filter_asset_keen": "Keen",
        "pesdk_filter_asset_legacyFilterCategory": "Legacy",
        "pesdk_filter_asset_lenin": "Lemon",
        "pesdk_filter_asset_litho": "Litho",
        "pesdk_filter_asset_lomo": "Lomo",
        "pesdk_filter_asset_lomo100": "Lomo 100",
        "pesdk_filter_asset_lucid": "Lucid",
        "pesdk_filter_asset_mellow": "Mellow",
        "pesdk_filter_asset_neat": "Neat",
        "pesdk_filter_asset_noGreen": "Pumpkin",
        "pesdk_filter_asset_orchid": "Solanus",
        "pesdk_filter_asset_pale": "Pale",
        "pesdk_filter_asset_pitched": "Pitched",
        "pesdk_filter_asset_plate": "Weathered",
        "pesdk_filter_asset_pro400": "Pro 400",
        "pesdk_filter_asset_quozi": "Quozi",
        "pesdk_filter_asset_sepiaHigh": "Sepia",
        "pesdk_filter_asset_settled": "Settled",
        "pesdk_filter_asset_sin": "Hard Stuff",
        "pesdk_filter_asset_smoothFilterCategory": "Smooth",
        "pesdk_filter_asset_soft": "Soft",
        "pesdk_filter_asset_steel": "Steel",
        "pesdk_filter_asset_summer": "Summer",
        "pesdk_filter_asset_sunset": "Golden",
        "pesdk_filter_asset_sx": "Pola SX",
        "pesdk_filter_asset_tender": "Tender",
        "pesdk_filter_asset_texas": "Oldtimer",
        "pesdk_filter_asset_twilight": "Twilight",
        "pesdk_filter_asset_vintageFilterCategory": "Vintage",
        "pesdk_filter_asset_warmFilterCategory": "Warm",
        "pesdk_filter_asset_winter": "Softy",
        "pesdk_filter_asset_x400": "Dusty",
        "pesdk_filter_button_none": "Без",
        "pesdk_filter_title_name": "Фильтр",
        "pesdk_focus_accessibility_blurIntensitySliderLabel": "Интенсивность размытия",
        "pesdk_focus_accessibility_decreaseFocusWidthAction": "Уменьшите ширину фокуса",
        "pesdk_focus_accessibility_disabledFocusLabel": "Без",
        "pesdk_focus_accessibility_focusAreaHint": "Дважды нажмите и удерживайте, чтобы переместить область фокусировки",
        "pesdk_focus_accessibility_gaussianFocusLabel": "Гауссово размывание",
        "pesdk_focus_accessibility_increaseFocusWidthAction": "Увеличьте ширину фокуса",
        "pesdk_focus_accessibility_linearFocusAreaLabel": "Линейная область размытия",
        "pesdk_focus_accessibility_linearFocusLabel": "Линейное размытие",
        "pesdk_focus_accessibility_mirroredFocusAreaLabel": "Зеркальная область размытия",
        "pesdk_focus_accessibility_mirroredFocusLabel": "Зеркальное размытие",
        "pesdk_focus_accessibility_radialFocusAreaLabel": "Радиальная облатсь размытия",
        "pesdk_focus_accessibility_radialFocusLabel": "Радиальное размытие",
        "pesdk_focus_accessibility_rotateLeftAction": "Поворот влево",
        "pesdk_focus_accessibility_rotateRightAction": "Поворот вправо",
        "pesdk_focus_button_disabled": "Без",
        "pesdk_focus_button_gaussian": "Гаусс",
        "pesdk_focus_button_linear": "Линейное",
        "pesdk_focus_button_mirrored": "Зеркальное",
        "pesdk_focus_button_radial": "Радиальное",
        "pesdk_focus_title_name": "Размытие",
        "pesdk_frame_accessibility_blackPassepartoutFrameLabel": "Черная рамка",
        "pesdk_frame_accessibility_diaFrameLabel": "Диаметр рамки",
        "pesdk_frame_accessibility_noFrameButtonLabel": "Без",
        "pesdk_frame_accessibility_opacityButtonLabel": "Непрозрачность",
        "pesdk_frame_accessibility_replaceButtonLabel": "Заменить рамку",
        "pesdk_frame_accessibility_whiteArtDecorFrameLabel": "Белый арт декор",
        "pesdk_frame_accessibility_widthButtonLabel": "Изменить ширину",
        "pesdk_frame_accessibility_woodPassepartoutFrameLabel": "Деревянная рамка",
        "pesdk_frame_button_none": "Без",
        "pesdk_frame_button_opacity": "Непрозрачность",
        "pesdk_frame_button_replace": "Заменить",
        "pesdk_frame_button_width": "Ширина",
        "pesdk_frame_text_frameDownloadError": "Невозможно загрузить рамку.",
        "pesdk_frame_title_name": "Рамка",
        "pesdk_frame_title_options": "Параметры рамки",
        "pesdk_overlay_accessibility_overlayIntensitySliderLabel": "Интенсивность наложения",
        "pesdk_overlay_asset_golden": "Золотой",
        "pesdk_overlay_asset_lightleak": "Луч света",
        "pesdk_overlay_asset_mosaic": "Мозаика",
        "pesdk_overlay_asset_paper": "Бумага",
        "pesdk_overlay_asset_rain": "Дождь",
        "pesdk_overlay_asset_vintage": "Винтажный",
        "pesdk_overlay_button_blendModeColorBurn": "Цвет Ожога",
        "pesdk_overlay_button_blendModeDarken": "Темный",
        "pesdk_overlay_button_blendModeHardLight": "Жесткий свет",
        "pesdk_overlay_button_blendModeLighten": "Свелый",
        "pesdk_overlay_button_blendModeMultiply": "Умножение",
        "pesdk_overlay_button_blendModeNormal": "Нормальный",
        "pesdk_overlay_button_blendModeOverlay": "Наложение",
        "pesdk_overlay_button_blendModeScreen": "Экран",
        "pesdk_overlay_button_blendModeSoftLight": "Мягкий свет",
        "pesdk_overlay_button_none": "Без",
        "pesdk_overlay_title_name": "Слой",
        "pesdk_sticker_accessibility_brightnessButtonLabel": "Яркость",
        "pesdk_sticker_accessibility_brightnessIntensitySliderLabel": "Яркость",
        "pesdk_sticker_accessibility_colorButtonLabel": "Цвет",
        "pesdk_sticker_accessibility_contrastButtonLabel": "Контраст",
        "pesdk_sticker_accessibility_contrastIntensitySliderLabel": "Контраст",
        "pesdk_sticker_accessibility_opacityButtonLabel": "Изменение непрозрачности",
        "pesdk_sticker_accessibility_opacityIntensitySliderLabel": "Непрозрачность",
        "pesdk_sticker_accessibility_replaceButtonLabel": "Заменить стикер",
        "pesdk_sticker_accessibility_rotateLeftAction": "Поворот влево",
        "pesdk_sticker_accessibility_rotateRightAction": "Поворот вправо",
        "pesdk_sticker_accessibility_saturationButtonLabel": "Насыщенность",
        "pesdk_sticker_accessibility_saturationIntensitySliderLabel": "Насыщенность",
        "pesdk_sticker_accessibility_spriteViewHint": "Дважды нажмите, чтобы выделить",
        "pesdk_sticker_accessibility_stickerSelectionHint": "Дважды нажмите и удерживайте для перемещения",
        "pesdk_sticker_accessibility_stickerSelectionLabel": "Выбраннаый стикер",
        "pesdk_sticker_accessibility_straightenButtonLabel": "Выпрямить",
        "pesdk_sticker_asset_alien": "Alien",
        "pesdk_sticker_asset_angel": "Angel",
        "pesdk_sticker_asset_angry": "Angry",
        "pesdk_sticker_asset_anxious": "Anxious",
        "pesdk_sticker_asset_arrow2": "Arrow 2",
        "pesdk_sticker_asset_arrow3": "Arrow 3",
        "pesdk_sticker_asset_asleep": "Asleep",
        "pesdk_sticker_asset_attention": "Attention",
        "pesdk_sticker_asset_babyChicken": "Baby Chicken",
        "pesdk_sticker_asset_badge1": "Badge 1",
        "pesdk_sticker_asset_badge11": "Badge 11",
        "pesdk_sticker_asset_badge12": "Badge 12",
        "pesdk_sticker_asset_badge13": "Badge 13",
        "pesdk_sticker_asset_badge15": "Badge 15",
        "pesdk_sticker_asset_badge18": "Badge 18",
        "pesdk_sticker_asset_badge19": "Badge 19",
        "pesdk_sticker_asset_badge20": "Badge 20",
        "pesdk_sticker_asset_badge28": "Badge 28",
        "pesdk_sticker_asset_badge32": "Badge 32",
        "pesdk_sticker_asset_badge35": "Badge 35",
        "pesdk_sticker_asset_badge36": "Badge 36",
        "pesdk_sticker_asset_badge4": "Badge 4",
        "pesdk_sticker_asset_badge6": "Badge 6",
        "pesdk_sticker_asset_badge8": "Badge 8",
        "pesdk_sticker_asset_batman": "Batman",
        "pesdk_sticker_asset_beer": "Beer",
        "pesdk_sticker_asset_black": "Black",
        "pesdk_sticker_asset_blue": "Blue",
        "pesdk_sticker_asset_blush": "Blush",
        "pesdk_sticker_asset_boxer": "Boxer",
        "pesdk_sticker_asset_business": "Business",
        "pesdk_sticker_asset_chicken": "Chicken",
        "pesdk_sticker_asset_cool": "Cool",
        "pesdk_sticker_asset_cry": "Cry",
        "pesdk_sticker_asset_deceased": "Deceased",
        "pesdk_sticker_asset_devil": "Devil",
        "pesdk_sticker_asset_duckface": "Duckface",
        "pesdk_sticker_asset_emoticonsStickerCategory": "Стикеры",
        "pesdk_sticker_asset_furious": "Furious",
        "pesdk_sticker_asset_grin": "Grin",
        "pesdk_sticker_asset_guitar": "Guitar",
        "pesdk_sticker_asset_harryPotter": "Harry Potter",
        "pesdk_sticker_asset_hippie": "Hippie",
        "pesdk_sticker_asset_hitman": "Hitman",
        "pesdk_sticker_asset_humourous": "Humourous",
        "pesdk_sticker_asset_idea": "Idea",
        "pesdk_sticker_asset_impatient": "Impatient",
        "pesdk_sticker_asset_kiss": "Kiss",
        "pesdk_sticker_asset_kisses": "Kisses",
        "pesdk_sticker_asset_laugh": "Laugh",
        "pesdk_sticker_asset_loudCry": "Loud Cry",
        "pesdk_sticker_asset_loving": "Loving",
        "pesdk_sticker_asset_masked": "Masked",
        "pesdk_sticker_asset_music": "Music",
        "pesdk_sticker_asset_nerd": "Nerd",
        "pesdk_sticker_asset_ninja": "Ninja",
        "pesdk_sticker_asset_notSpeakingToYou": "Not speaking to you",
        "pesdk_sticker_asset_personalStickerCategory": "Custom",
        "pesdk_sticker_asset_pig": "Pig",
        "pesdk_sticker_asset_pumpkin": "Pumpkin",
        "pesdk_sticker_asset_question": "Question",
        "pesdk_sticker_asset_rabbit": "Rabbit",
        "pesdk_sticker_asset_sad": "Sad",
        "pesdk_sticker_asset_shapesStickerCategory": "Формы",
        "pesdk_sticker_asset_sick": "Sick",
        "pesdk_sticker_asset_skateboard": "Skateboard",
        "pesdk_sticker_asset_skull": "Skull",
        "pesdk_sticker_asset_sleepy": "Sleepy",
        "pesdk_sticker_asset_smile": "Smile",
        "pesdk_sticker_asset_smoking": "Smoking",
        "pesdk_sticker_asset_sobbing": "Sobbing",
        "pesdk_sticker_asset_spray1": "Spray 1",
        "pesdk_sticker_asset_spray3": "Spray 3",
        "pesdk_sticker_asset_spray4": "Spray 4",
        "pesdk_sticker_asset_star": "Star",
        "pesdk_sticker_asset_steamingFurious": "Steaming Furious",
        "pesdk_sticker_asset_sunbathing": "Sunbathing",
        "pesdk_sticker_asset_tired": "Tired",
        "pesdk_sticker_asset_tongueOutWink": "Tongue out wink",
        "pesdk_sticker_asset_wave": "Wave",
        "pesdk_sticker_asset_wideGrin": "Wide Grin",
        "pesdk_sticker_asset_wink": "Wink",
        "pesdk_sticker_asset_wrestler": "Wrestler",
        "pesdk_sticker_button_brightness": "Яркость",
        "pesdk_sticker_button_color": "Цвет",
        "pesdk_sticker_button_contrast": "Контраст",
        "pesdk_sticker_button_opacity": "Прозрачность",
        "pesdk_sticker_button_replace": "Заменить",
        "pesdk_sticker_button_saturation": "Насыщенность",
        "pesdk_sticker_button_straighten": "Выпрямление",
        "pesdk_sticker_text_stickerDownloadError": "Ошибка при установке Стикера",
        "pesdk_sticker_title_color": "Цвет Стикера",
        "pesdk_sticker_title_name": "Стикер",
        "pesdk_sticker_title_options": "Настройки стикера",
        "pesdk_textDesign_accessibility_spriteViewHint": "Нажмите дважды, чтобы выбрать",
        "pesdk_textDesign_accessibility_textDesignDescriptionLabel": "Text Design Layout",
        "pesdk_textDesign_accessibility_textDesignSelectionLabel": "Макет дизайна текста",
        "pesdk_textDesign_asset_blocks": "Blocks",
        "pesdk_textDesign_asset_blocksCondensed": "Blocks Condensed",
        "pesdk_textDesign_asset_blocksLight": "Blocks Light",
        "pesdk_textDesign_asset_celebrate": "Celebrate",
        "pesdk_textDesign_asset_celebrateSimple": "Celebrate Simple",
        "pesdk_textDesign_asset_equalWidth": "Equal Width",
        "pesdk_textDesign_asset_equalWidthFat": "Equal Width Fat",
        "pesdk_textDesign_asset_masked": "Masked",
        "pesdk_textDesign_asset_maskedBadge": "Masked Badge",
        "pesdk_textDesign_asset_maskedSpeechBubble": "Masked Speech Bubble",
        "pesdk_textDesign_asset_maskedSpeechBubbleComic": "Masked Speech Bubble Comic",
        "pesdk_textDesign_asset_multiline": "Multiline",
        "pesdk_textDesign_asset_particles": "Particles",
        "pesdk_textDesign_asset_rotated": "Rotated",
        "pesdk_textDesign_asset_sunshine": "Sunshine",
        "pesdk_textDesign_asset_watercolor": "Watercolor",
        "pesdk_textDesign_title_addTextDesign": "Добавить дизайн тексту",
        "pesdk_textDesign_title_changeTextDesign": "Сменить дизайн текста",
        "pesdk_textDesign_title_name": "Дизайн текста",
        "pesdk_text_accessibility_alignmentButtonLabel": "Центровка",
        "pesdk_text_accessibility_backgroundColorButtonLabel": "Цвет фона",
        "pesdk_text_accessibility_colorButtonLabel": "Цвет",
        "pesdk_text_accessibility_decreaseBoundingBoxAction": "Уменьшить",
        "pesdk_text_accessibility_fontButtonLabel": "Шрифт",
        "pesdk_text_accessibility_fontPreviewToggleHint": "Нажмите дважды, чтобы показать или спрятать пример шрифта",
        "pesdk_text_accessibility_fontPreviewToggleLabel": "Переключить пример шрифта",
        "pesdk_text_accessibility_increaseBoundingBoxAction": "Увеличить",
        "pesdk_text_accessibility_rotateLeftAction": "Влево",
        "pesdk_text_accessibility_rotateRightAction": "Вправо",
        "pesdk_text_accessibility_spriteViewHint": "Нажмите дважды, чтобы выбрать",
        "pesdk_text_accessibility_straightenButtonLabel": "Выпрямление",
        "pesdk_text_accessibility_textSelectionHint": "Нажмите дважды и удерживайте, чтобы передвинуть",
        "pesdk_text_accessibility_textSelectionLabel": "Выбранный текст",
        "pesdk_text_button_alignment": "Центровка",
        "pesdk_text_button_backgroundColor": "Увет фона",
        "pesdk_text_button_bringToFront": "Наверх",
        "pesdk_text_button_color": "Цвет",
        "pesdk_text_button_font": "Шрифт",
        "pesdk_text_button_straighten": "Выпрямление",
        "pesdk_text_title_addText": "Добавить текст",
        "pesdk_text_title_backgroundColor": "Цвет Фона",
        "pesdk_text_title_changeText": "Изменить",
        "pesdk_text_title_font": "Шрифт",
        "pesdk_text_title_name": "Текст",
        "pesdk_text_title_options": "Настройки текста",
        "pesdk_text_title_textColor": "Цвет Текста",
        "pesdk_transform_accessibility_cropSelectionViewLabel": "Выделенная область",
        "pesdk_transform_accessibility_croppingAreaHint": "Нажмите дважды и удерживайте, чтобы настроить область",
        "pesdk_transform_accessibility_croppingHandleBottomLabel": "Нижняя грань обрезки",
        "pesdk_transform_accessibility_croppingHandleBottomLeftLabel": "Нижняя левая часть обрезки",
        "pesdk_transform_accessibility_croppingHandleBottomRightLabel": "Нижняя правая часть обрезки",
        "pesdk_transform_accessibility_croppingHandleLeftLabel": "Левая часть обрезки",
        "pesdk_transform_accessibility_croppingHandleRightLabel": "Правая часть обрезки",
        "pesdk_transform_accessibility_croppingHandleTopLabel": "Верхняя часть обрезки",
        "pesdk_transform_accessibility_croppingHandleTopLeftLabel": "Верхняя левая часть обрезки",
        "pesdk_transform_accessibility_croppingHandleTopRightLabel": "Верхняя правая часть обрезки",
        "pesdk_transform_accessibility_flipButtonHint": "Нажмите дважды, чтобы перевернуть картинку",
        "pesdk_transform_accessibility_flipButtonLabel": "Перевернуть",
        "pesdk_transform_accessibility_rotateAspectRatioHint": "Нажмите дважды, чтобы изменить соотношение сторон",
        "pesdk_transform_accessibility_rotateButtonHint": "Нажмите дважды, чтобы повернуть",
        "pesdk_transform_accessibility_rotateButtonLabel": "Повернуть",
        "pesdk_transform_accessibility_scalePickerLabel": "Обрезка и наклон",
        "pesdk_transform_asset_freeCrop": "Свое",
        "pesdk_transform_asset_square": "Квадрат",
        "pesdk_transform_button_reset": "Сброс",
        "pesdk_transform_title_name": "Обрезать",
        "pesdk_trim_title_name": "Подрезать",
    ]
}
